name: Create Relaese
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version  (ie 5.5.0)'
        required: true

jobs:
  createrelease:
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
    - run: echo "previous_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo '')" >> $GITHUB_ENV
    - name: Create Tag
      id: create_tag
      uses: jaywcjlove/create-tag-action@main
      if: env.previous_tag
      with:
        package-path: ./package.json
        # Github Token
        token: ${{ secrets.GITHUB_TOKEN }}
        # Version (e.g. v0.1.0)
        version: v${{ github.event.inputs.versionName }}
        # Tag message
        message: "aaa"
        
    - name: Release Changelog Builder
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v3.7.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
      with:
        tag_name: v${{ github.event.inputs.versionName }}
        body: ${{steps.build_changelog.outputs.changelog}}
